### ISSUE TITLE
pwn-drive & history-pig & growser-grab

### ISSUE THREAD

**Issue by WastelandSYS** [atomiczsec/My-Payloads#4]
I have followed the exact steps but sadly no output file is ever sent to my dropbox
i am using a rpi pico w against my windows 10 home . 

Absolutely wish someone would do some videos on these and set up too. Either that or write a good detailed description of how to

Really the ones with dropbox  aren't working...

**Comment by atomiczsec** [comment]
Can you provide some error messages?
