### ISSUE TITLE
browser.exe Yandex Browser trouble

### ISSUE THREAD

**Issue by FLozyXD** [atomiczsec/My-Payloads#8]
Hello. Just tried lauching a badusb payload with browser devil and it seems like Yandex somehow prevents you from exporting passwords. Any suggestions about it?

The table should look like this:
UserName,Password,LoginURL,CreateDate

But the password section is blank. Just curious.

**Comment by atomiczsec** [comment]
try grabbing the new exe from the source:

https://github.com/moonD4rk/HackBrowserData
